# Generated by Django 5.2.4 on 2025-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('scam_type', models.CharField(choices=[('phishing', 'Phishing'), ('fraud_call', 'Fraud Call'), ('fake_shop', 'Fake Online Shop'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
