# Generated by Django 5.2.4 on 2025-08-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
