# Generated by Django 5.1.7 on 2025-08-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_scamreport_latitude_scamreport_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamreport',
            name='amount_lost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='evidence/'),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='scammer_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
