# Generated by Django 5.1.7 on 2026-04-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_scamreport_amount_lost_scamreport_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scamreport',
            options={'ordering': ['-date_reported']},
        ),
        migrations.AddField(
            model_name='scamreport',
            name='admin_note',
            field=models.TextField(blank=True, default='', help_text='Internal note from admin (not shown publicly)'),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='bank_involved',
            field=models.CharField(blank=True, default='', help_text='Bank name targeted or used in the fraud', max_length=100),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='incident_date',
            field=models.DateField(blank=True, help_text='Date when the scam occurred', null=True),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='incident_time',
            field=models.TimeField(blank=True, help_text='Approximate time when the scam occurred', null=True),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='pin_code',
            field=models.CharField(blank=True, default='', help_text='6-digit Indian PIN code', max_length=6),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='platform',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('phone_call', 'Phone Call'), ('sms', 'SMS'), ('email', 'Email'), ('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('website', 'Fake Website'), ('truecaller', 'Truecaller / Unknown Number'), ('other', 'Other')], default='', help_text='Channel used by scammer to contact victim', max_length=50),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='platform_detail',
            field=models.CharField(blank=True, default='', help_text='Free text: specific app, website URL, email domain etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Auto-generated unique reference, e.g. SS-00423', max_length=20),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='scam_subtype',
            field=models.CharField(blank=True, choices=[('kyc_update', 'KYC / Aadhaar Update'), ('bank_verify', 'Bank Account Verification'), ('irctc_refund', 'IRCTC / Travel Refund'), ('upi_link', 'Fake UPI Payment Link'), ('electricity', 'Electricity Bill Scam'), ('delivery', 'Fake Delivery / Courier'), ('impersonation', 'Government / Officer Impersonation'), ('tech_support', 'Fake Tech Support'), ('lottery', 'Lottery / Prize Scam'), ('loan_offer', 'Fake Loan Offer'), ('fake_product', 'Fake Product Listing'), ('non_delivery', 'Payment Taken, No Delivery'), ('discount_fraud', 'Fake Discount / Coupon'), ('screen_share', 'Screen Share / Remote Access'), ('qr_scam', 'QR Code Fraud'), ('emi_fraud', 'EMI / Loan App Fraud'), ('stock_tip', 'Fake Stock Tips'), ('crypto_fraud', 'Crypto / NFT Fraud'), ('ponzi', 'Ponzi / MLM Scheme'), ('other', 'Other / Not Listed')], default='', help_text='More specific sub-category of the scam', max_length=50),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='scammer_account',
            field=models.CharField(blank=True, default='', help_text='Bank account number if known', max_length=50),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='scammer_ifsc',
            field=models.CharField(blank=True, default='', help_text="IFSC code of scammer's bank", max_length=11),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='scammer_upi',
            field=models.CharField(blank=True, default='', help_text="Scammer's UPI ID (e.g. name@okaxis)", max_length=255),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2, help_text='Severity level set by system or admin'),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='scamreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('escalated', 'Escalated to Authorities')], default='pending', help_text='Moderation status', max_length=20),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='amount_lost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount lost in INR', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='Hide reporter identity from public view'),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True, help_text='When this report was submitted'),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='description',
            field=models.TextField(help_text='Full description of the incident'),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='evidence',
            field=models.FileField(blank=True, help_text='Screenshot, recording, or document', null=True, upload_to='evidence/'),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='location',
            field=models.CharField(help_text='City or place', max_length=255),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='scam_type',
            field=models.CharField(choices=[('phishing', 'Phishing'), ('fraud_call', 'Fraud Call / Vishing'), ('fake_shop', 'Fake Online Shop'), ('upi_fraud', 'UPI / Banking Fraud'), ('investment', 'Investment / Crypto Scam'), ('job_scam', 'Job Offer Scam'), ('ransomware', 'Ransomware / Malware'), ('sextortion', 'Sextortion / Blackmail'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='scammer_contact',
            field=models.CharField(blank=True, default='', help_text='Phone, email, or username of scammer', max_length=255),
        ),
        migrations.AlterField(
            model_name='scamreport',
            name='title',
            field=models.CharField(help_text='Brief title / platform name', max_length=200),
        ),
        migrations.AddIndex(
            model_name='scamreport',
            index=models.Index(fields=['scam_type'], name='reports_sca_scam_ty_4a0772_idx'),
        ),
        migrations.AddIndex(
            model_name='scamreport',
            index=models.Index(fields=['platform'], name='reports_sca_platfor_db3815_idx'),
        ),
        migrations.AddIndex(
            model_name='scamreport',
            index=models.Index(fields=['location'], name='reports_sca_locatio_1badd4_idx'),
        ),
        migrations.AddIndex(
            model_name='scamreport',
            index=models.Index(fields=['status'], name='reports_sca_status_36f2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='scamreport',
            index=models.Index(fields=['-date_reported'], name='reports_sca_date_re_a84795_idx'),
        ),
        migrations.AddIndex(
            model_name='scamreport',
            index=models.Index(fields=['reference_number'], name='reports_sca_referen_77d0b1_idx'),
        ),
    ]
