# Generated by Django 5.1.7 on 2026-04-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_scamreport_options_scamreport_admin_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamreport',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Auto-generated unique reference, e.g. SS-00423', max_length=20, unique=True),
        ),
    ]
